"""Subprocess-backed admin workflow runner.

This is intentionally small but production-shaped: workflow names are whitelisted,
commands are generated by code, logs are persisted as JSONL, and process handles
stay in memory only for live cancel/stream behavior.
"""

from __future__ import annotations

import json
import os
import subprocess
import threading
import time
import uuid
from collections import OrderedDict
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from finevent.api.artifacts import artifact_relative_path, get_workspace_root
from finevent.api.serialization import to_jsonable
from finevent.api.workflow_registry.catalog import build_workflow_steps
from finevent.api.workflow_registry.types import WorkflowStep

RUN_STATUSES = {"queued", "running", "success", "failed", "canceled", "interrupted"}
PROCESS_REGISTRY: dict[str, subprocess.Popen[str]] = {}
REGISTRY_LOCK = threading.Lock()
PENDING_RUNS: OrderedDict[str, list[WorkflowStep]] = OrderedDict()
ACTIVE_RUN_IDS: set[str] = set()
RUNNER_CONDITION = threading.Condition()
DISPATCHER_THREAD: threading.Thread | None = None


class RunQueueFullError(RuntimeError):
    """Raised when the admin run queue is full."""


@dataclass
class RunState:
    run_id: str
    workflow_name: str
    status: str
    config: dict[str, Any]
    steps: list[dict[str, Any]]
    created_at: str
    started_at: str | None = None
    finished_at: str | None = None
    current_step_id: str | None = None
    summary: dict[str, Any] = field(default_factory=dict)
    error_message: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return to_jsonable(
            {
                "run_id": self.run_id,
                "workflow_name": self.workflow_name,
                "status": self.status,
                "config": self.config,
                "steps": self.steps,
                "created_at": self.created_at,
                "started_at": self.started_at,
                "finished_at": self.finished_at,
                "current_step_id": self.current_step_id,
                "summary": self.summary,
                "error_message": self.error_message,
            }
        )


def create_run(workflow_name: str, config: dict[str, Any]) -> RunState:
    run_id = f"admin_run_{_utc_compact()}_{uuid.uuid4().hex[:8]}"
    steps = build_workflow_steps(workflow_name, config, run_id=run_id)
    run_state = RunState(
        run_id=run_id,
        workflow_name=workflow_name,
        status="queued",
        config=config,
        created_at=_utc_now(),
        steps=[_step_to_state(step) for step in steps],
    )
    ensure_dispatcher_started()
    with RUNNER_CONDITION:
        if len(PENDING_RUNS) >= _max_queue_size():
            raise RunQueueFullError(
                "Admin run queue is full. Increase FINEVENT_MAX_QUEUE_SIZE or wait "
                "for queued runs to start."
            )
        _write_run_state(run_state)
        PENDING_RUNS[run_state.run_id] = steps
        RUNNER_CONDITION.notify_all()
    return run_state


def ensure_dispatcher_started() -> None:
    global DISPATCHER_THREAD
    with RUNNER_CONDITION:
        if DISPATCHER_THREAD is not None and DISPATCHER_THREAD.is_alive():
            return
        DISPATCHER_THREAD = threading.Thread(
            target=_dispatch_loop,
            name="finevent-admin-dispatcher",
            daemon=True,
        )
        DISPATCHER_THREAD.start()


def reconcile_interrupted_runs() -> int:
    """Mark stale queued/running runs as interrupted after an API restart."""

    interrupted_count = 0
    with RUNNER_CONDITION:
        PENDING_RUNS.clear()
        ACTIVE_RUN_IDS.clear()
        RUNNER_CONDITION.notify_all()
    with REGISTRY_LOCK:
        PROCESS_REGISTRY.clear()

    for path in sorted(_admin_runs_root().glob("*/run.json")):
        run_state = _read_run_state(path)
        if run_state is None or run_state.status not in {"queued", "running"}:
            continue
        timestamp = _utc_now()
        run_state.status = "interrupted"
        run_state.finished_at = timestamp
        run_state.error_message = "Server restarted before this run completed."
        for step in run_state.steps:
            if step.get("status") in {"queued", "running"}:
                step["status"] = "interrupted"
                step["finished_at"] = timestamp
                step["error_message"] = run_state.error_message
        _write_run_state(run_state)
        _log_event(run_state.run_id, "", "WARN", "system", run_state.error_message)
        interrupted_count += 1
    return interrupted_count


def list_runs(
    *,
    status: str | None = None,
    workflow_name: str | None = None,
    limit: int = 50,
    offset: int = 0,
) -> dict[str, Any]:
    runs = [_read_run_state(path) for path in sorted(_admin_runs_root().glob("*/run.json"))]
    runs = [run for run in runs if run is not None]
    if status:
        runs = [run for run in runs if run.status == status]
    if workflow_name:
        runs = [run for run in runs if run.workflow_name == workflow_name]
    runs.sort(key=lambda run: run.created_at, reverse=True)
    return {
        "items": [run.to_dict() for run in runs[offset : offset + limit]],
        "limit": limit,
        "offset": offset,
        "total": len(runs),
    }


def get_run(run_id: str) -> RunState | None:
    return _read_run_state(_run_dir(run_id) / "run.json")


def cancel_run(run_id: str) -> RunState | None:
    run_state = get_run(run_id)
    if run_state is None:
        return None
    with RUNNER_CONDITION:
        was_pending = PENDING_RUNS.pop(run_id, None) is not None
        if was_pending:
            RUNNER_CONDITION.notify_all()
    with REGISTRY_LOCK:
        process = PROCESS_REGISTRY.get(run_id)
    if process is not None and process.poll() is None:
        process.terminate()
        _log_event(run_id, run_state.current_step_id or "", "WARN", "system", "Cancel requested.")
    elif was_pending:
        _log_event(run_id, "", "WARN", "system", "Queued run canceled before execution.")
    run_state.status = "canceled"
    run_state.finished_at = _utc_now()
    run_state.error_message = "Canceled by admin request."
    for step in run_state.steps:
        if step.get("status") in {"queued", "running"}:
            step["status"] = "canceled"
            step["finished_at"] = run_state.finished_at
    _write_run_state(run_state)
    return run_state


def read_run_logs(
    run_id: str,
    *,
    step_id: str | None = None,
    level: str | None = None,
    limit: int = 200,
    offset: int = 0,
) -> dict[str, Any]:
    log_path = _log_path(run_id)
    rows: list[dict[str, Any]] = []
    if log_path.exists():
        with log_path.open("r", encoding="utf-8") as file:
            for line in file:
                try:
                    row = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if step_id and row.get("step_id") != step_id:
                    continue
                if level and row.get("level") != level:
                    continue
                rows.append(row)
    return {
        "run_id": run_id,
        "items": rows[offset : offset + limit],
        "limit": limit,
        "offset": offset,
        "total": len(rows),
    }


def stream_run_logs(run_id: str) -> Any:
    position = 0
    while True:
        log_path = _log_path(run_id)
        if log_path.exists():
            with log_path.open("r", encoding="utf-8") as file:
                file.seek(position)
                while True:
                    line = file.readline()
                    if not line:
                        break
                    position = file.tell()
                    yield f"data: {line.strip()}\n\n"
        run_state = get_run(run_id)
        if run_state is None or run_state.status in {
            "success",
            "failed",
            "canceled",
            "interrupted",
        }:
            break
        time.sleep(0.5)


def _dispatch_loop() -> None:
    while True:
        with RUNNER_CONDITION:
            while not PENDING_RUNS or len(ACTIVE_RUN_IDS) >= _max_concurrent_runs():
                RUNNER_CONDITION.wait()
            run_id, steps = PENDING_RUNS.popitem(last=False)
            ACTIVE_RUN_IDS.add(run_id)
        worker = threading.Thread(
            target=_execute_run_and_release,
            args=(run_id, steps),
            name=f"finevent-admin-{run_id}",
            daemon=True,
        )
        worker.start()


def _execute_run_and_release(run_id: str, steps: list[WorkflowStep]) -> None:
    try:
        _execute_run(run_id, steps)
    finally:
        with RUNNER_CONDITION:
            ACTIVE_RUN_IDS.discard(run_id)
            RUNNER_CONDITION.notify_all()


def _execute_run(run_id: str, steps: list[WorkflowStep]) -> None:
    run_state = get_run(run_id)
    if run_state is None:
        return
    if run_state.status == "canceled":
        return
    run_state.status = "running"
    run_state.started_at = _utc_now()
    _write_run_state(run_state)
    _log_event(run_id, "", "INFO", "system", f"Run started: {run_state.workflow_name}")

    for step in steps:
        run_state = get_run(run_id)
        if run_state is None or run_state.status == "canceled":
            return
        run_state.current_step_id = step.step_id
        _update_step(run_state, step.step_id, status="running", started_at=_utc_now())
        _write_run_state(run_state)
        _log_event(run_id, step.step_id, "INFO", "system", f"Command: {' '.join(step.command)}")
        exit_code = _run_subprocess(run_id, step)
        run_state = get_run(run_id)
        if run_state is None:
            return
        if run_state.status == "canceled":
            return
        artifacts = _existing_artifacts(step.expected_artifacts)
        if exit_code == 0:
            _update_step(
                run_state,
                step.step_id,
                status="success",
                exit_code=exit_code,
                finished_at=_utc_now(),
                artifact_paths=artifacts,
            )
            _write_run_state(run_state)
            continue
        _update_step(
            run_state,
            step.step_id,
            status="failed",
            exit_code=exit_code,
            finished_at=_utc_now(),
            artifact_paths=artifacts,
            error_message=f"Process exited with code {exit_code}.",
        )
        run_state.status = "failed"
        run_state.finished_at = _utc_now()
        run_state.error_message = f"Step {step.step_id} failed with exit code {exit_code}."
        _write_run_state(run_state)
        _log_event(run_id, step.step_id, "ERROR", "system", run_state.error_message)
        return

    run_state = get_run(run_id)
    if run_state is None:
        return
    run_state.status = "success"
    run_state.finished_at = _utc_now()
    run_state.current_step_id = None
    run_state.summary = {
        "success_step_count": sum(1 for step in run_state.steps if step.get("status") == "success"),
        "failed_step_count": sum(1 for step in run_state.steps if step.get("status") == "failed"),
    }
    _write_run_state(run_state)
    _log_event(run_id, "", "INFO", "system", "Run completed successfully.")


def _run_subprocess(run_id: str, step: WorkflowStep) -> int:
    env = os.environ.copy()
    src_path = str(get_workspace_root() / "src")
    env["PYTHONPATH"] = src_path + os.pathsep + env.get("PYTHONPATH", "")
    process = subprocess.Popen(
        step.command,
        cwd=get_workspace_root(),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=env,
    )
    with REGISTRY_LOCK:
        PROCESS_REGISTRY[run_id] = process
    try:
        assert process.stdout is not None
        for line in process.stdout:
            _log_event(run_id, step.step_id, "INFO", "stdout", line.rstrip())
        return int(process.wait())
    finally:
        with REGISTRY_LOCK:
            PROCESS_REGISTRY.pop(run_id, None)


def _step_to_state(step: WorkflowStep) -> dict[str, Any]:
    return {
        "step_id": step.step_id,
        "milestone": step.milestone,
        "name": step.name,
        "command": step.command,
        "status": "queued",
        "exit_code": None,
        "started_at": None,
        "finished_at": None,
        "artifact_paths": [],
        "error_message": None,
    }


def _update_step(run_state: RunState, step_id: str, **updates: Any) -> None:
    for step in run_state.steps:
        if step.get("step_id") == step_id:
            step.update(updates)
            return


def _existing_artifacts(paths: tuple[str, ...]) -> list[str]:
    artifacts: list[str] = []
    workspace_root = get_workspace_root()
    for path in paths:
        candidate = (workspace_root / path).resolve()
        if candidate.exists() and candidate.is_relative_to(workspace_root):
            artifacts.append(artifact_relative_path(candidate))
    return artifacts


def _write_run_state(run_state: RunState) -> None:
    run_dir = _run_dir(run_state.run_id)
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "run.json").write_text(
        json.dumps(run_state.to_dict(), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _read_run_state(path: Path) -> RunState | None:
    if not path.exists():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    if not isinstance(payload, dict):
        return None
    return RunState(
        run_id=str(payload.get("run_id") or path.parent.name),
        workflow_name=str(payload.get("workflow_name") or ""),
        status=str(payload.get("status") or "failed"),
        config=dict(payload.get("config") or {}),
        steps=list(payload.get("steps") or []),
        created_at=str(payload.get("created_at") or ""),
        started_at=payload.get("started_at"),
        finished_at=payload.get("finished_at"),
        current_step_id=payload.get("current_step_id"),
        summary=dict(payload.get("summary") or {}),
        error_message=payload.get("error_message"),
    )


def _log_event(run_id: str, step_id: str, level: str, source: str, message: str) -> None:
    log_path = _log_path(run_id)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    event = {
        "timestamp": _utc_now(),
        "run_id": run_id,
        "step_id": step_id,
        "level": level,
        "source": source,
        "message": message,
    }
    with log_path.open("a", encoding="utf-8") as file:
        file.write(json.dumps(event, ensure_ascii=False, sort_keys=True) + "\n")


def _run_dir(run_id: str) -> Path:
    return _admin_runs_root() / run_id


def _admin_runs_root() -> Path:
    return get_workspace_root() / "runs" / "admin"


def _log_path(run_id: str) -> Path:
    return _run_dir(run_id) / "logs" / "events.jsonl"


def _max_concurrent_runs() -> int:
    return max(1, _int_env("FINEVENT_MAX_CONCURRENT_RUNS", 1))


def _max_queue_size() -> int:
    return max(0, _int_env("FINEVENT_MAX_QUEUE_SIZE", 20))


def _int_env(key: str, default: int) -> int:
    raw_value = os.getenv(key)
    if raw_value is None:
        return default
    try:
        return int(raw_value)
    except ValueError:
        return default


def _utc_now() -> str:
    return datetime.now(tz=UTC).isoformat()


def _utc_compact() -> str:
    return datetime.now(tz=UTC).strftime("%Y%m%dT%H%M%SZ")
