"""Dependency-free database table catalog.

The catalog is a lightweight source of truth for table names and key columns.
SQLAlchemy Core metadata in `schema.py` should stay aligned with this catalog,
while the existing raw SQL sync modules can keep using explicit statements.
"""

from __future__ import annotations

from finevent.types import JsonDict

BASELINE_SQL_FILES = (
    "001_articles.sql",
    "002_ticker_dictionary.sql",
    "003_event_labels.sql",
    "004_retrieval.sql",
    "005_event_patterns.sql",
    "006_extraction_runs.sql",
    "007_workflow_reports.sql",
)

TABLE_COLUMNS: dict[str, tuple[str, ...]] = {
    "articles": (
        "article_id",
        "source",
        "url",
        "raw_html_path",
        "title",
        "published_at",
        "author",
        "clean_text_path",
        "content_hash",
        "language",
        "created_at",
    ),
    "article_metadata": (
        "article_id",
        "tickers_hint",
        "company_names_hint",
        "sector_hints",
        "event_keywords",
        "event_type_hints",
        "event_subtype_hints",
        "metadata_confidence",
        "parse_warnings",
    ),
    "ticker_companies": (
        "ticker",
        "company_name",
        "sector",
        "exchange",
        "status",
        "source_note",
        "source_url",
        "last_verified_at",
        "created_at",
        "updated_at",
    ),
    "ticker_company_aliases": (
        "alias_id",
        "ticker",
        "alias",
        "alias_norm",
        "created_at",
    ),
    "ticker_dictionary_sync_runs": (
        "sync_run_id",
        "source_type",
        "source_path",
        "upserted_companies",
        "upserted_aliases",
        "started_at",
        "completed_at",
        "status",
        "error",
    ),
    "event_labeling_runs": (
        "labeling_run_id",
        "label_schema_version",
        "teacher_model",
        "prompt_version",
        "source_path",
        "gold_count",
        "rejected_count",
        "status",
        "created_at",
        "completed_at",
    ),
    "event_label_documents_gold": (
        "article_id",
        "document_label",
        "label_reason",
        "label_schema_version",
        "label_source",
        "teacher_model",
        "prompt_version",
        "labeling_run_id",
        "warnings",
        "model_info",
        "validation_warnings",
        "raw_label",
        "created_at",
        "updated_at",
    ),
    "events_gold": (
        "event_id",
        "article_id",
        "ticker",
        "company_name",
        "event_type",
        "event_subtype",
        "event_summary",
        "event_reason",
        "event_arguments",
        "impact_sentiment",
        "evidence_span",
        "source_url",
        "published_at",
        "confidence",
        "label_schema_version",
        "label_source",
        "teacher_model",
        "prompt_version",
        "labeling_run_id",
        "created_at",
        "updated_at",
    ),
    "event_label_rejections": (
        "rejection_id",
        "article_id",
        "label_schema_version",
        "teacher_model",
        "prompt_version",
        "labeling_run_id",
        "validation_errors",
        "raw_output",
        "created_at",
    ),
    "financial_news_documents": (
        "article_id",
        "source",
        "url",
        "title",
        "published_at",
        "content_hash",
        "language",
        "tickers_hint",
        "company_names_hint",
        "sector_hints",
        "event_keywords",
        "event_type_hints",
        "event_subtype_hints",
        "created_at",
        "updated_at",
    ),
    "financial_news_chunks": (
        "chunk_id",
        "article_id",
        "chunk_level",
        "chunk_index",
        "parent_chunk_id",
        "text",
        "title",
        "source",
        "url",
        "published_at",
        "content_hash",
        "chunk_hash",
        "text_word_count",
        "tickers_hint",
        "company_names_hint",
        "sector_hints",
        "event_keywords",
        "event_type_hints",
        "event_subtype_hints",
        "pattern_refs",
        "paragraph_start",
        "paragraph_end",
        "metadata",
        "version",
        "created_at",
        "updated_at",
    ),
    "financial_news_chunk_patterns": (
        "chunk_id",
        "article_id",
        "pattern_id",
        "event_id",
        "event_type",
        "event_subtype",
        "pattern_kind",
        "document_label",
        "match_strategy",
        "match_score",
        "pattern_ref",
        "created_at",
    ),
    "financial_news_chunk_embeddings": (
        "embedding_id",
        "chunk_id",
        "article_id",
        "embedding_model",
        "embedding_dimension",
        "content_hash",
        "chunk_hash",
        "embedding",
        "status",
        "error",
        "created_at",
    ),
    "event_patterns": (
        "pattern_id",
        "article_id",
        "document_label",
        "pattern_kind",
        "event_id",
        "event_type",
        "event_subtype",
        "ticker",
        "company_name",
        "impact_sentiment",
        "input_excerpt",
        "gold_output",
        "pattern_text",
        "evidence_span",
        "event_arguments",
        "explanation_brief",
        "source",
        "url",
        "published_at",
        "teacher_model",
        "teacher_prompt_version",
        "auto_validation_status",
        "validation_errors",
        "metadata",
        "version",
        "created_at",
        "updated_at",
    ),
    "retrieval_runs": (
        "retrieval_run_id",
        "article_id",
        "retrieval_config",
        "query_plan",
        "metrics",
        "warnings",
        "source_path",
        "output_path",
        "created_at",
    ),
    "retrieval_run_contexts": (
        "retrieval_run_id",
        "rank",
        "chunk_id",
        "article_id",
        "score",
        "score_breakdown",
        "context",
        "pattern_refs",
        "created_at",
    ),
    "extraction_runs": (
        "run_id",
        "article_id",
        "document_label",
        "workflow_config",
        "model_name",
        "prompt_version",
        "retrieval_config",
        "pattern_ids",
        "retrieval_run_id",
        "context_chunk_ids",
        "draft_output",
        "final_output",
        "validation_issues",
        "verification_report",
        "hallucination_metrics",
        "warnings",
        "errors",
        "run_dir",
        "created_at",
        "completed_at",
    ),
    "extraction_node_traces": (
        "trace_id",
        "run_id",
        "node",
        "status",
        "latency_ms",
        "input_summary",
        "output_summary",
        "warnings",
        "errors",
        "created_at",
    ),
    "workflow_reports": (
        "report_id",
        "run_id",
        "workflow_name",
        "step_id",
        "path",
        "name",
        "kind",
        "size_bytes",
        "content_text",
        "content_json",
        "content_truncated",
        "metadata",
        "created_at",
        "updated_at",
    ),
}


def table_names() -> tuple[str, ...]:
    return tuple(TABLE_COLUMNS)


def catalog_summary() -> JsonDict:
    return {
        "table_count": len(TABLE_COLUMNS),
        "tables": {table: list(columns) for table, columns in TABLE_COLUMNS.items()},
        "baseline_sql_files": list(BASELINE_SQL_FILES),
    }
